add load token from config

diff --git a/github b/github
--- a/github
+++ b/github
@@ -1,24 +1,24 @@
 #!/bin/bash
 
-# get repo name
-repoName=$1
+config=~/.config/github-cli
 
-# default username
-username="shovity"
-
-# get username if exists
-if [ "$2" != "" ]; then
-  username="$2"
-fi
+#check config file
+test [ ! -f $config ] && echo 'config not found' && exit 1
 
 # check repo name exist
-test -z $repoName && echo "Repo name required." 1>&2 && exit 1
+test -z $1 && echo "Repo name required." 1>&2 && exit 1
+
+#require config
+source $config
+
+# get repo name
+repoName=$1
 
 echo 'create github repositries "'$username/$repoName'"'
 echo '...'
 
 # send api create repo github
-curl -u $username https://api.github.com/user/repos -d '{"name":"'$repoName'"}'
+curl -v -H "Authorization: token $token" https://api.github.com/user/repos -d '{"name":"$repoName"}'
 
 while [ true ]; do
   read -p "Init git local and remote [ssh/https]? (s/h/n): " next
